### PR TITLE
➕ Add prettier

### PR DESCRIPTION
**Pull request by mewiemers**
https://prettier.io/docs/en/install.html
install prettier with `npm i -D prettier`
Added `prettierrc.json`
Added `prettierignore` to ignore build artifacts
Prettified code

### CODE REVIEW

**Comment by m-wiemers** [comment]
should it be named `prettierc.json`?

**Review by m-wiemers — APPROVED** [review]
gj 🎺

**Review by RonjaMeinecke — APPROVED** [review]
lgtm💪

**Comment by JuKahl** [comment]
You could improve your comment by using the bulleted list 💪

**Pull request merged**
