### PR TITLE
➕ Add ESLINT

### PR DESCRIPTION
**Pull request by mewiemers**
[ESLintconfig]https://eslint.org/docs/user-guide/getting-started
[Next.js import type] https://nextjs.org/docs/basic-features/typescript#api-routes

[next.js props validation]https://nextjs.org/docs/basic-features/typescript#custom-app

- config eslint
- add script for eslint check
- add rules for ignore specific eslint rules

### CODE REVIEW

**Review by saschahaselhuhn — APPROVED** [review]
gj

**Review by fgottes — APPROVED** [review]
LGTM! :)

You could add the commands we used to install eslint in addition :P

**Review by fre-ben — APPROVED** [review]
GJ! 🚀 
Your Markdown Links are not working correctly.
```
[example](link)
```
Code should look like this :)

**Review by JuKahl — APPROVED** [review]
gj 💪

**Review by SilviaBarcellini — APPROVED** [review]
Great! 👍

**Review by christophvogel — APPROVED** [review]
GJ 👍

**Review by m-wiemers — APPROVED** [review]
I would not have done better

**Pull request merged**
